version: "3"

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - api-gateway
    restart: always

  frontend:
    build: ./frontend-service
    expose:
      - "3000"
    depends_on:
      - identity-service
    restart: always

  identity-service:
    build: ./identity-service
    expose:
      - "5000"
    restart: always

  api-gateway:
    build: ./api-gateway
    expose:
      - "8000"
    depends_on:
      - identity-service
    restart: always
